name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add VPS key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "[51.89.150.209]:6666 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP4UWxTGWJczjsMCy0TTI7spTiBi3gTekT3qbUSk/G85" >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6666
          script: |
            cd /var/www/html/bformation.chevrolliernathan.fr
            git pull origin main
